# Generated by Django 3.2.9 on 2021-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Music'},
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
