# Generated by Django 3.2.9 on 2021-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('POP MUSIC', 'Pop Music'), ('HIPHOP MUSIC', 'Hip Hop Music'), ('ELECTRONIC DANCE MUSIC', 'Electronic Dance Music'), ('CLASSICAL MUSIC', 'Classical Music'), ('HOUSE MUSIC', 'House Music'), ('TRAP MUSIC', 'Trap Music'), ('JAZZ', 'Jazz'), ('R&B', 'R&B')], max_length=90),
        ),
    ]
