# Generated by Django 3.2.9 on 2021-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20211122_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(),
        ),
    ]
