version: "3"

services:
  db:
    image: postgres
    container_name: "musicApi_db"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: .
    container_name: "musicApi_web"
    # command: python /code/manage.py runserver 0.0.0.0:8000
    # command: gunicorn --workers 5 --threads 2 musicApi.wsgi
    command: gunicorn musicApi.asgi:application -k uvicorn.workers.UvicornWorker # gunicorn with uvicorn command

    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - DROPBOX_CONSUMER_KEY=${DROPBOX_CONSUMER_KEY}
      - DROPBOX_CONSUMER_SECRET=${DROPBOX_CONSUMER_SECRET}
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db