# Generated by Django 3.2.9 on 2021-12-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_genre'),
        ('user_playlists', '0002_alter_userplaylistsong_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylistsong',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music'),
        ),
    ]
