# Generated by Django 3.2.9 on 2021-12-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_userplaylistsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplaylistsong',
            old_name='playlist',
            new_name='user_playlist',
        ),
    ]
