# Generated by Django 3.2.9 on 2021-12-05 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_alter_music_album'),
        ('playlist', '0003_rename_playlist_userplaylistsong_user_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylistsong',
            name='user_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist_song', to='playlist.userplaylist'),
        ),
        migrations.CreateModel(
            name='UserFavourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_music', to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
