# Generated by Django 3.2.9 on 2021-12-05 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_album'),
        ('playlist', '0004_auto_20211205_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourites',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='music.music'),
        ),
    ]
